spring:
  application:
      name: employeeservice
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: '8085'

      
#Discover server access
eureka:
   client:
     serviceUrl:
       defaultZone: http://localhost:1111/eureka/